---
# tasks file for ELK
- name: Install ELK Dependencies (ubuntu)
  apt:
    name:
      - openjdk-11-jdk
      - apt-transport-https
      - curl
      - gpgv
      - gpgsm
      - gnupg-l10n
      - gnupg 
      - dirmngr
    state: latest
#ELK Dependencies <END>

#Elasticsearch Installation <START>
- name: Get PGP Key (ubuntu)
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch repository into sources list (ubuntu)
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Elasticsearch (ubuntu)
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes
#Elasticsearch Installation <END>

#Elasticsearch Configuration <Start>
- name: Configure Elasticsearch change cluster name (ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "cluster.name: demo-elk"
    state: present

- name: Configure Elasticsearch give cluster descriptive name (ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "node.name: elk-1"
    state: present

- name: Configure Elasticsearch Add network.host (ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: 0.0.0.0"
    state: present

- name: Configure Elasticsearch Add http.port (ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "http.port: 9200"
    state: present

- name: Configure Elasticsearch Add discovery.type (ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "discovery.type: single-node"
    state: present

- name: Creating an empty file for startup-timeout.conf 1 of 2 (ubuntu)
  file:
    path: "/etc/systemd/system/elasticsearch.service.d"
    state: directory

- name: Creating an empty file for startup-timeout.conf 2 of 2 (ubuntu)
  file:
    path: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    state: touch

- name: Prevent systemd service start operation from timing out (ubuntu)
  copy:
    dest: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    content: |
      [Service]
      TimeoutStartSec=3min
#Elasticsearch Configuration <END>

#Elasticsearch Enable Services <START>
- name: Run daemon-reload for elasticsearch (ubuntu)
  systemd: daemon_reload=yes

- name: Enable service Elasticsearch and ensure it is not masked (ubuntu)
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running (ubuntu)
  systemd: state=started name=elasticsearch
#Elasticsearch Enable Services <END>

#Logstash Installation <START>
- name: Install Logstash (ubuntu)
  apt:
    name: logstash
    state: latest
    update_cache: yes
#Logstash Installation <END>

#Logstash Enable Services <START>
- name: Run daemon-reload for logstash (ubuntu)
  systemd: daemon_reload=yes

- name: Enable service logstash (ubuntu)
  systemd:
    name: logstash
    enabled: yes

- name: ensure logstash is running (ubuntu)
  systemd: state=started name=logstash
#Logstash Enable Services <END>

#Kibana Installation <START>
- name: Install Kibana (ubuntu)
  apt:
    name: kibana
    state: latest
    update_cache: yes
#Kibana Installation <END>

#Kibana Configuration <START>
- name: Configure Kibana Add server.port (ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: "server.port: 5601"
    state: present

- name: Configure Kibana Add server.host (ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.host: “0.0.0.0”'
    state: present

- name: Configure Kibana Add server.name (ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.name: “demo-kibana”'
    state: present

- name: Configure Kibana Add elasticsearch.hosts (ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'elasticsearch.hosts: [“http://0.0.0.0:9200"]'
    state: present
#Kibana Configuration <END>

#Kibana Enable Services <START>
- name: Run daemon-reload for kibana (ubuntu)
  systemd: daemon_reload=yes

- name: Enable service Kibana (ubuntu)
  systemd:
    name: kibana
    enabled: yes
#Kibana Enable Services <END>

#Start Elasticsearch & Kibana <START>
- name: Start Elasticsearch & Kibana (ubuntu)
  shell: systemctl start elasticsearch && systemctl start kibana
#Start Elasticsearch & Kibana <END>
